#############################################################################
# Makefile for building: mes
<<<<<<< HEAD
# Generated by qmake (2.01a) (Qt 4.7.4) on: lun feb 18 09:28:32 2013
=======
# Generated by qmake (2.01a) (Qt 4.7.4) on: lun mar 4 08:40:38 2013
>>>>>>> ab210070f27e857d96696d3b2896d8ab005b9ff9
# Project:  mes.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile mes.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtWebKit -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ventanaprincipal.cpp \
		dialogoparaimportararchivoscsv.cpp \
		libcsv.c \
		dialogoparaguardararchivodedatossiono.cpp moc_ventanaprincipal.cpp \
		moc_dialogoparaimportararchivoscsv.cpp \
		moc_dialogoparaguardararchivodedatossiono.cpp
OBJECTS       = main.o \
		ventanaprincipal.o \
		dialogoparaimportararchivoscsv.o \
		libcsv.o \
		dialogoparaguardararchivodedatossiono.o \
		moc_ventanaprincipal.o \
		moc_dialogoparaimportararchivoscsv.o \
		moc_dialogoparaguardararchivodedatossiono.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		mes.pro
QMAKE_TARGET  = mes
DESTDIR       = 
TARGET        = mes

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ventanaprincipal.h ui_dialogoparaimportararchivoscsv.h ui_dialogoparaguardararchivodedatossiono.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mes.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile mes.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile mes.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mes1.0.0 || $(MKDIR) .tmp/mes1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mes1.0.0/ && $(COPY_FILE) --parents ventanaprincipal.h dialogoparaimportararchivoscsv.h textos.h csv.h variablesglobales.h dialogoparaguardararchivodedatossiono.h manejodearchivoscsv.h .tmp/mes1.0.0/ && $(COPY_FILE) --parents main.cpp ventanaprincipal.cpp dialogoparaimportararchivoscsv.cpp libcsv.c dialogoparaguardararchivodedatossiono.cpp .tmp/mes1.0.0/ && $(COPY_FILE) --parents ventanaprincipal.ui dialogoparaimportararchivoscsv.ui dialogoparaguardararchivodedatossiono.ui .tmp/mes1.0.0/ && (cd `dirname .tmp/mes1.0.0` && $(TAR) mes1.0.0.tar mes1.0.0 && $(COMPRESS) mes1.0.0.tar) && $(MOVE) `dirname .tmp/mes1.0.0`/mes1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mes1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ventanaprincipal.cpp moc_dialogoparaimportararchivoscsv.cpp moc_dialogoparaguardararchivodedatossiono.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ventanaprincipal.cpp moc_dialogoparaimportararchivoscsv.cpp moc_dialogoparaguardararchivodedatossiono.cpp
moc_ventanaprincipal.cpp: ventanaprincipal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ventanaprincipal.h -o moc_ventanaprincipal.cpp

moc_dialogoparaimportararchivoscsv.cpp: dialogoparaimportararchivoscsv.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogoparaimportararchivoscsv.h -o moc_dialogoparaimportararchivoscsv.cpp

moc_dialogoparaguardararchivodedatossiono.cpp: dialogoparaguardararchivodedatossiono.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogoparaguardararchivodedatossiono.h -o moc_dialogoparaguardararchivodedatossiono.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ventanaprincipal.h ui_dialogoparaimportararchivoscsv.h ui_dialogoparaguardararchivodedatossiono.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ventanaprincipal.h ui_dialogoparaimportararchivoscsv.h ui_dialogoparaguardararchivodedatossiono.h
ui_ventanaprincipal.h: ventanaprincipal.ui
	/usr/bin/uic-qt4 ventanaprincipal.ui -o ui_ventanaprincipal.h

ui_dialogoparaimportararchivoscsv.h: dialogoparaimportararchivoscsv.ui
	/usr/bin/uic-qt4 dialogoparaimportararchivoscsv.ui -o ui_dialogoparaimportararchivoscsv.h

ui_dialogoparaguardararchivodedatossiono.h: dialogoparaguardararchivodedatossiono.ui
	/usr/bin/uic-qt4 dialogoparaguardararchivodedatossiono.ui -o ui_dialogoparaguardararchivodedatossiono.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ventanaprincipal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ventanaprincipal.o: ventanaprincipal.cpp ventanaprincipal.h \
		ui_ventanaprincipal.h \
		variablesglobales.h \
		dialogoparaguardararchivodedatossiono.h \
		dialogoparaimportararchivoscsv.h \
		textos.h \
		csv.h \
		manejodearchivoscsv.h \
		ui_dialogoparaimportararchivoscsv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ventanaprincipal.o ventanaprincipal.cpp

dialogoparaimportararchivoscsv.o: dialogoparaimportararchivoscsv.cpp dialogoparaimportararchivoscsv.h \
		ui_dialogoparaimportararchivoscsv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoparaimportararchivoscsv.o dialogoparaimportararchivoscsv.cpp

libcsv.o: libcsv.c csv.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o libcsv.o libcsv.c

dialogoparaguardararchivodedatossiono.o: dialogoparaguardararchivodedatossiono.cpp dialogoparaguardararchivodedatossiono.h \
		ui_dialogoparaguardararchivodedatossiono.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogoparaguardararchivodedatossiono.o dialogoparaguardararchivodedatossiono.cpp

moc_ventanaprincipal.o: moc_ventanaprincipal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ventanaprincipal.o moc_ventanaprincipal.cpp

moc_dialogoparaimportararchivoscsv.o: moc_dialogoparaimportararchivoscsv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoparaimportararchivoscsv.o moc_dialogoparaimportararchivoscsv.cpp

moc_dialogoparaguardararchivodedatossiono.o: moc_dialogoparaguardararchivodedatossiono.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogoparaguardararchivodedatossiono.o moc_dialogoparaguardararchivodedatossiono.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

